"""empty message

Revision ID: 07c401553e90
Revises: 662a634697a3
Create Date: 2023-04-23 21:15:25.372905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07c401553e90'
down_revision = '662a634697a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=260),
               existing_nullable=False)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=260),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=260),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=260),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=260),
               existing_nullable=False)

    with op.batch_alter_table('teas', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=260),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teas', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=260),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###
