"""empty message

Revision ID: 0abf893ec21e
Revises: 30bd224e576a
Create Date: 2023-04-14 17:01:57.433325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abf893ec21e'
down_revision = '30bd224e576a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tea_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])
        batch_op.create_foreign_key(None, 'teas', ['tea_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tea_id')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
