"""Add phone number and address to employee model

Revision ID: 104d3008e125
Revises: db2b848c288d
Create Date: 2023-03-27 17:15:17.395312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104d3008e125'
down_revision = 'db2b848c288d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
