"""empty message

Revision ID: 1c6fed79516e
Revises: 5af4174f7081
Create Date: 2023-04-13 12:23:34.666389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c6fed79516e'
down_revision = '5af4174f7081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_leave_days', sa.Integer(), nullable=True))
        batch_op.drop_column('reamining_leave_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reamining_leave_days', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('remaining_leave_days')

    # ### end Alembic commands ###
