"""empty message

Revision ID: 295eb925d538
Revises: f3d2f73e5811
Create Date: 2023-04-16 17:40:27.548975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295eb925d538'
down_revision = 'f3d2f73e5811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['leave_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
