"""empty message

Revision ID: a97cdea0b55e
Revises: 2aca5e7a899d
Create Date: 2023-04-08 13:25:18.063434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97cdea0b55e'
down_revision = '2aca5e7a899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_progress', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('in_progress')

    # ### end Alembic commands ###
